### ISSUE TITLE
Package Release To-Do

### ISSUE THREAD

**Issue by jknowles** [jknowles/metaframe#3]
- [x] summary method for `meta.data` and `meta.frame` objects
- [x] print method for `meta.data` and `meta.frame` objects
- [x] str method for `meta.data` and `meta.frame` objects
- [ ] `write.csv`, `write.xlsx` methods for `meta.data` and `meta.frame` objects
- [x] `document` method for `data.table` objects
- [x] `add_` constructor functions to append metadata
- [ ] `codebook` function tested and compatible with `meta.data` and `meta.frame` objects
- [ ] README that shows package utility
- [ ] Vignette showing the key concepts behind `metaframe`
